### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTitle' of undefined

### ISSUE THREAD

**Issue by jerone** [benjamindean/atom-notifier#5]
**Steps to reproduce:**
1. Install [sync-settings](https://atom.io/packages/sync-settings) package
2. [Setup backup credentials](https://github.com/Hackafe/atom-sync-settings#setup)
3. Backup settings
4. Restart Atom
5. An popup should appear saying that you have the latest backup

Instead of [showing the success-popup](https://github.com/Hackafe/atom-sync-settings/blob/master/lib/sync-settings.coffee#L97) this error is shown. The popup is shown at the moment Atom is loaded and the package is activated.

**Atom Version**: 1.0.3
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [atom-notifier](https://github.com/benjamindean/atom-notifier) package, v0.3.3
### Stack Trace

Uncaught TypeError: Cannot read property 'getTitle' of undefined

```
At /C:/Users/jerone/.atom/packages/atom-notifier/lib/notifier.coffee:82

TypeError: Cannot read property 'getTitle' of undefined
  at Object.module.exports.send (C:\Users\jerone\.atom\packages\atom-notifier\lib\notifier.coffee:66:81)
  at C:\Users\jerone\.atom\packages\atom-notifier\lib\notifier.coffee:61:86
  at Emitter.module.exports.Emitter.emit (C:\Users\jerone\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at NotificationManager.module.exports.NotificationManager.addNotification (C:\Users\jerone\AppData\Local\atom\app-1.0.3\resources\app.asar\src\notification-manager.js:54:20)
  at NotificationManager.module.exports.NotificationManager.addSuccess (C:\Users\jerone\AppData\Local\atom\app-1.0.3\resources\app.asar\src\notification-manager.js:29:19)
  at Object.SyncSettings.notifyBackupUptodate (C:\Users\jerone\.atom\packages\sync-settings\lib\sync-settings.coffee:97:24)
  at C:\Users\jerone\.atom\packages\sync-settings\lib\sync-settings.coffee:64:12
  at C:\Users\jerone\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\gists.js:342:17
  at callCallback (C:\Users\jerone\.atom\packages\sync-settings\node_modules\github\index.js:743:17)
  at IncomingMessage.<anonymous> (C:\Users\jerone\.atom\packages\sync-settings\node_modules\github\index.js:796:25)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "tool-bar-main",
      "toolbar-basic",
      "enhanced-tabs"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
about, v1.0.1
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.9
atom-notifier, v0.3.3
atom-yeoman, v0.3.11
color-picker, v2.0.11
editorconfig, v1.0.1
file-icons, v1.6.2
flex-tool-bar, v0.4.4
foldername-tabs, v0.1.5
gutter-shadow, v0.5.0
indentation-indicator, v0.6.0
json-schema, v0.1.11
language-actionscript3, v0.3.0
language-jade, v0.6.2
language-sln, v0.1.0
linter, v1.2.4
linter-coffeelint, v1.0.1
markdown-scroll-sync, v0.4.0
menu-manager, v0.4.2
minimap, v4.12.1
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-selection, v4.3.0
new-tab, v0.4.1
omnisharp-atom, v0.23.1
open-conemu-here, v0.5.0
open-recent, v2.3.0
project-view, v0.1.2
soft-wrap-indicator, v0.7.0
spell-check, v0.59.0
symbols-tree-view, v0.9.3
sync-settings, v0.6.0
tool-bar, v0.1.8
travis-ci-status, v0.16.0
useful-context-menu, v0.2.1

# Dev
flex-tool-bar, v0.4.4
new-tab, v0.4.1
sync-settings, v0.6.0
timecop, v0.31.0
tool-bar, v0.1.8
tree-view, v0.179.0
```

**Comment by benjamindean** [comment]
@jerone I will look for it as soon as I can. Thank you for your feedback!

**Comment by benjamindean** [comment]
@jerone Seems to be fixed with the latest commit.

**Comment by jerone** [comment]
Confirmed working. Great work.
