### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTitle' of undefined

### ISSUE THREAD

**Issue by jerone** [benjamindean/atom-notifier#6]
I'm getting random error messages on startup (see below).

Aldo not tested, I think the following change should solve it:

``` diff
@@ -62,7 +62,7 @@ module.exports =
         @loadNotifier()
         type = Notification.getType()
         title = Notification.getMessage()
-        message = Notification.getDetail() ? atom.workspace.getActivePaneItem().getTitle()
+        message = Notification.getDetail() ? atom.workspace.getActivePaneItem().getTitle?()
         params =
             'title': title
             'message': message
```

---

**Atom Version**: 1.0.11
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-notifier](https://github.com/benjamindean/atom-notifier) package, v0.4.1
### Stack Trace

Uncaught TypeError: Cannot read property 'getTitle' of undefined

```
At C:\Users\jwm\.atom\packages\atom-notifier\lib\notifier.coffee:81

TypeError: Cannot read property 'getTitle' of undefined
  at Object.module.exports.send (C:\Users\jwm\.atom\packages\atom-notifier\lib\notifier.coffee:65:81)
  at C:\Users\jwm\.atom\packages\atom-notifier\lib\notifier.coffee:59:35
  at Emitter.module.exports.Emitter.emit (C:\Users\jwm\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at NotificationManager.module.exports.NotificationManager.addNotification (C:\Users\jwm\AppData\Local\atom\app-1.0.11\resources\app.asar\src\notification-manager.js:54:20)
  at NotificationManager.module.exports.NotificationManager.addSuccess (C:\Users\jwm\AppData\Local\atom\app-1.0.11\resources\app.asar\src\notification-manager.js:29:19)
  at Object.SyncSettings.notifyBackupUptodate (C:\Users\jwm\.atom\packages\sync-settings\lib\sync-settings.coffee:97:24)
  at C:\Users\jwm\.atom\packages\sync-settings\lib\sync-settings.coffee:64:12
  at C:\Users\jwm\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\gists.js:342:17
  at callCallback (C:\Users\jwm\.atom\packages\sync-settings\node_modules\github\index.js:743:17)
  at IncomingMessage.<anonymous> (C:\Users\jwm\.atom\packages\sync-settings\node_modules\github\index.js:796:25)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```
### Commands

```
     -0:04.9.0 window:toggle-dev-tools (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "tool-bar-main",
      "toolbar-basic",
      "enhanced-tabs"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
about, v1.1.0
atom-jade, v0.3.0
atom-material-syntax, v0.2.3
atom-material-ui, v0.6.0
atom-minify, v0.4.1
atom-notifier, v0.4.1
atom-yeoman, v0.3.13
color-picker, v2.0.11
editorconfig, v1.1.1
file-icons, v1.6.9
flex-tool-bar, v0.5.0
foldername-tabs, v0.1.5
gutter-shadow, v0.5.0
imdone-atom, v1.1.37
indentation-indicator, v0.6.0
json-schema, v0.1.13
language-actionscript3, v0.3.0
language-jade, v0.6.2
language-sln, v0.1.0
linter, v1.4.3
linter-coffeelint, v1.0.2
markdown-scroll-sync, v0.4.2
menu-manager, v0.4.3
minimap, v4.13.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-selection, v4.3.0
new-tab, v0.4.1
omnisharp-atom, v0.24.0
open-conemu-here, v0.5.0
open-recent, v2.3.0
project-view, v0.1.2
soft-wrap-indicator, v0.7.0
symbols-tree-view, v0.9.3
sync-settings, v0.6.0
tool-bar, v0.1.8
travis-ci-status, v0.16.0
useful-context-menu, v0.2.1

# Dev
sync-settings, v0.6.0
```

**Comment by benjamindean** [comment]
@jerone Seems like getTitle sometimes called before workspace is initialized. Published a patch. Thank you!

**Comment by benjamindean** [comment]
@jerone Looks like it's finally fixed. I was able to reproduce the error by opening folder on a remote server with Atom. Editor hangs for about a minute-two and then, throws this error. Due to atom.workspace postponed initialization.
